services: 
  sonarr: 
    image: lscr.io/linuxserver/sonarr:latest 
    container_name: sonarr 
    environment: 
      - PUID=0 
      - PGID=0 
      - TZ=Asia/Kolkata 
    volumes: 
      - .\config:/config 
      - E:\Media\:/Media  
    ports: 
      - 8989:8989 
    restart: unless-stopped 
    privileged: true 
 