services:
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - .\config:/app/config
    restart: unless-stopped
